            IDENT           parallel_phong$c
**********************************************
*      Assemble with Cal Version 2.0         *
*                                            *
* Generated by Std C   4.0.3                 *
*           on 09/18/06 at 14:01:19          *
*                                            *
**********************************************
* ALLOW UNDERSCORES IN IDENTIFIERS
            EDIT            OFF
            FORMAT          NEW
@DATA       SECTION         DATA,CM
@DATA       =               W.*
            CON             O'0000000001400000000000
            CON             O'0710000000000000000000
            CON             O'0734000000000000000000
            CON             O'0665413226700000000000        ;main          24
            CON             O'0000000000000001200004        ;trbk tbl      24
            VWD             32/0,32/P.main                  ;trbk tbl      24
            CON             O'0040001000000000000011        ;trbk tbl      24
            CON             O'0000000000000000000012        ;trbk tbl      24
            CON             O'0000000000000000000006        ;trbk tbl      24
            BSSZ            1                               ;trbk tbl      24
            SECTION         *
@CODE       SECTION         CODE
@CODE       =               P.*
L3          =               P.*                             ;              24
            B02             A2                              ;new base      24
            B66             A3                              ;stk top       24
            B01             A6                              ;arg base      24
            A7              P.L4                            ;ofrn rtn      24
            B00             A7                              ;return        24
            A6              @DATA                           ;              24
            J               $STKOFEN                        ;$STKOFEN      24
main        =               P.*                             ;              24
            A0              @DATA+4                         ;(trbk)        24
            B77             A0                              ;(trbk)        24
            A1              6                               ;num Bs        24
            A0              B66                             ;stk top       24
            A2              B66                             ;stk tmp       24
            A4              B67                             ;stk limt      24
            0,A0            B77,A1                          ;              24
            A7              9                               ;stk size      24
            A3              A2+A7                           ;              24
            A0              A4-A3                           ;              24
            JAM             L3                              ;overflow      24
            B02             A2                              ;new base      24
            B66             A3                              ;new top       24
            B01             A6                              ;arg base      24
L4          =               P.*                             ;ofrn rtn      24
            A7              B01                             ;regs          14
            A6              2,A7                            ;              14
            A4              B02                             ;s_bt_sp       14
            S7              1073741838                      ;              14
            S7              S7<32                           ;              14
            S6              2                               ;              14
            A5              6                               ;              14
            S5              S7!S6                           ;              14
            B03             A6                              ;regs          14
            A6              A5+A4                           ;              14
            A5              B03                             ;regs          14
            S7              1,A5                            ;              14
            S6              @DATA+1                         ;              14
            6,A4            S5                              ;              14
            8,A4            S6                              ;              14
            7,A4            S7                              ;              14
            R               P.fopen                         ;fopen         14
            A7              B03                             ;regs          15
            S7              2,A7                            ;              15
            A5              B02                             ;s_bt_sp       15
            S6              1073741839                      ;              15
            S6              S6<32                           ;              15
            S5              2                               ;              15
            S4              @DATA+2                         ;              15
            A7              6                               ;              15
            S3              S6!S5                           ;              15
            A6              S1                              ;              14
            6,A5            S3                              ;              15
            B03             A6                              ;s_bt_sp       15
            8,A5            S4                              ;              15
            7,A5            S7                              ;              15
            A6              A7+A5                           ;              15
            R               P.fopen                         ;              15
            S7              1073741842                      ;              18
            A4              B03                             ;s_bt_sp       18
            A5              B02                             ;s_bt_sp       18
            S7              S7<32                           ;              18
            A7              S1                              ;              15
            S6              2                               ;              18
            A6              6                               ;              18
            S5              S7!S6                           ;              18
            6,A5            S5                              ;              18
            7,A5            A4                              ;              18
            8,A5            A7                              ;              18
            A6              A6+A5                           ;              18
            B04             A7                              ;regs          18
            R               P.render                        ;render        18
            S7              1073741845                      ;              21
            A5              B03                             ;s_bt_sp       21
            A6              B02                             ;s_bt_sp       21
            S7              S7<32                           ;              21
            S6              1                               ;              21
            A7              6                               ;              21
            S5              S7!S6                           ;              21
            6,A6            S5                              ;              21
            7,A6            A5                              ;              21
            A6              A7+A6                           ;              21
            R               P.fclose                        ;fclose        21
            S7              1073741846                      ;              22
            A5              B04                             ;s_bt_sp       22
            A6              B02                             ;s_bt_sp       22
            S7              S7<32                           ;              22
            S6              1                               ;              22
            A7              6                               ;              22
            S5              S7!S6                           ;              22
            6,A6            S5                              ;              22
            7,A6            A5                              ;              22
            A6              A7+A6                           ;              22
            R               P.fclose                        ;              22
            S1              0                               ;              24
            A0              B02                             ;              24
            A1              6                               ;num Bs        24
            B66             A0                              ;              24
            B77,A1          0,A0                            ;              24
            J               B00                             ;              24
            EXT             $STKOFEN:p
            EXT             fclose:p
            EXT             fopen:p
            START           main
            EXT             render:p
            END
